export const VQ_TEXTURE_ENCODE_TYPE = 3;

export const TEXTURE_COLOR_SIZE = 2;
export const VQ_CODEBOOK_ENTRY_COUNT = 256;
export const VQ_CODEBOOK_VECTOR_LENGTH = 4;
export const VQ_CODEBOOK_BYTE_SIZE =
  TEXTURE_COLOR_SIZE * VQ_CODEBOOK_VECTOR_LENGTH * VQ_CODEBOOK_ENTRY_COUNT;
