const mvc2CharacterIds = {
  '00': 'Ryu',
  '01': 'Zangief',
  '02': 'Guile',
  '03': 'Morrigan',
  '04': 'Anakaris',
  '05': 'Strider Hiryu',
  '06': 'Cyclops',
  '07': 'Wolverine',
  '08': 'Psylocke',
  '09': 'Iceman',
  '0A': 'Rogue',
  '0B': 'Captain America',
  '0C': 'Spider-Man',
  '0D': 'Hulk',
  '0E': 'Venom',
  '0F': 'Doctor Doom',
  '10': 'Tron Bonne',
  '11': 'Jill',
  '12': 'Hayato',
  '13': 'Ruby Heart',
  '14': 'SonSon',
  '15': 'Amingo',
  '16': 'Marrow',
  '17': 'Cable',
  '18': 'Abyss 1',
  '19': 'Abyss 2',
  '1A': 'Abyss 3',
  '1B': 'Chun-Li',
  '1C': 'Mega Man',
  '1D': 'Roll',
  '1E': 'Akuma',
  '1F': 'B.B. Hood',
  '20': 'Felicia',
  '21': 'Charlie Nash',
  '22': 'Sakura',
  '23': 'Dan',
  '24': 'Cammy',
  '25': 'Dhalsim',
  '26': 'M. Bison',
  '27': 'Ken',
  '28': 'Gambit',
  '29': 'Juggernaut',
  '2A': 'Storm',
  '2B': 'Sabretooth',
  '2C': 'Magneto',
  '2D': 'Shuma-Gorath',
  '2E': 'War Machine',
  '2F': 'Silver Samurai',
  '30': 'Omega Red',
  '31': 'Spiral',
  '32': 'Colossus',
  '33': 'Iron Man',
  '34': 'Sentinel',
  '35': 'Blackheart',
  '36': 'Thanos',
  '37': 'Jin',
  '38': 'Captain Commando',
  '39': 'Wolverine Bone Claw',
  '3A': 'Servbot'
} as const;

export default mvc2CharacterIds;
